--------------------------------------------------------
--  Datei erstellt -Mittwoch-Mai-11-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type ADRESSET
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST49"."ADRESSET" as Object
  ( Adresse_Strasse VARCHAR2(50),
    Adresse_Haus_Nr VARCHAR(25),
    Adresse_Ort VARCHAR(50),
    Adresse_Plz NUMBER(5,0)) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type KONTENLISTET
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST49"."KONTENLISTET" as Table of REF KontoT;

/
--------------------------------------------------------
--  DDL for Type KONTOT
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST49"."KONTOT" as Object
  ( Konto_Art VARCHAR(50),
    Konto_Nr NUMBER(9,0),
    Konto_Stand NUMBER) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type KUNDET_V1
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST49"."KUNDET_V1" as Object 
  ( KUNDE_V1_Nr NUMBER(4,0),
    KUNDE_V1_Name VARCHAR2(50),
    KUNDE_V1_Status VARCHAR2(25),
    KUNDE_V1_Adresse REF AdresseT,
    KUNDE_V1_Konten_Liste KontenListeT) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type ZWEIGSTELLET_V1
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST49"."ZWEIGSTELLET_V1" as Object
  ( ZWEIGSTELLE_V1_Name VARCHAR2(50),
    ZWEIGSTELLE_V1_Leiter VARCHAR(50),
    ZWEIGSTELLE_V1_Adresse REF AdresseT,
    ZWEIGSTELLE_V1_Konten_Liste KontenListeT) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Table KONTO
--------------------------------------------------------

  CREATE TABLE "DBST49"."KONTO" OF "DBST49"."KONTOT" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KUNDE_V1
--------------------------------------------------------

  CREATE TABLE "DBST49"."KUNDE_V1" OF "DBST49"."KUNDET_V1" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 NESTED TABLE "KUNDE_V1_KONTEN_LISTE" STORE AS "KUNDE_V1_KONTEN_LISTE_NT"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) RETURN AS VALUE;
-- Wiedergabe von TABLE DDL für Objekt DBST49.KUNDE_V1_KONTEN_LISTE_NT nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE TABLE KUNDE_V1_KONTEN_LISTE_NT 
(
 ) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS
--------------------------------------------------------
--  DDL for Table ZWEIGSTELLE_V1
--------------------------------------------------------

  CREATE TABLE "DBST49"."ZWEIGSTELLE_V1" OF "DBST49"."ZWEIGSTELLET_V1" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 NESTED TABLE "ZWEIGSTELLE_V1_KONTEN_LISTE" STORE AS "ZWEIG_V1_KONTEN_LISTE_NT"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) RETURN AS VALUE;
-- Wiedergabe von TABLE DDL für Objekt DBST49.ZWEIG_V1_KONTEN_LISTE_NT nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE TABLE ZWEIG_V1_KONTEN_LISTE_NT 
(
 ) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS
--------------------------------------------------------
--  DDL for View DMRS_INSTALLATION
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "DBST49"."DMRS_INSTALLATION" ("DMRS_PERSISTENCE_VERSION", "DMRS_REPORTS_VERSION", "CREATED_ON") AS 
  select 1.6 DMRS_Persistence_Version, 1.0 DMRS_Reports_Version, to_timestamp('2016/05/09 16:10:00','YYYY/MM/DD HH24:MI:SS') Created_On from dual with read only;
--------------------------------------------------------
--  DDL for View DMRV_REPORTS_VERSION_1_0
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "DBST49"."DMRV_REPORTS_VERSION_1_0" ("DMRS_PERSISTENCE_VERSION", "DMRS_REPORTS_VERSION", "CREATED_ON") AS 
  select 1.6 DMRS_Persistence_Version, 1.0 DMRS_Reports_Version, to_timestamp('2016/05/09 16:10:00','YYYY/MM/DD HH24:MI:SS') Created_On from dual with read only;
REM INSERTING into DBST49.KONTO
SET DEFINE OFF;
Insert into DBST49.KONTO (KONTO_ART,KONTO_NR,KONTO_STAND) values ('S','120768','234,56');
Insert into DBST49.KONTO (KONTO_ART,KONTO_NR,KONTO_STAND) values ('G','678453','-456,78');
Insert into DBST49.KONTO (KONTO_ART,KONTO_NR,KONTO_STAND) values ('G','348973','12567,56');
Insert into DBST49.KONTO (KONTO_ART,KONTO_NR,KONTO_STAND) values ('G','987654','789,65');
Insert into DBST49.KONTO (KONTO_ART,KONTO_NR,KONTO_STAND) values ('S','745363','-23,67');
REM INSERTING into DBST49.KUNDE_V1
SET DEFINE OFF;
REM INSERTING into DBST49.ZWEIGSTELLE_V1
SET DEFINE OFF;
REM INSERTING into DBST49.DMRS_INSTALLATION
SET DEFINE OFF;
Insert into DBST49.DMRS_INSTALLATION (DMRS_PERSISTENCE_VERSION,DMRS_REPORTS_VERSION,CREATED_ON) values ('1,6','1',to_timestamp('09.05.16 16:10:00,000000000','DD.MM.RR HH24:MI:SSXFF'));
REM INSERTING into DBST49.DMRV_REPORTS_VERSION_1_0
SET DEFINE OFF;
Insert into DBST49.DMRV_REPORTS_VERSION_1_0 (DMRS_PERSISTENCE_VERSION,DMRS_REPORTS_VERSION,CREATED_ON) values ('1,6','1',to_timestamp('09.05.16 16:10:00,000000000','DD.MM.RR HH24:MI:SSXFF'));
--------------------------------------------------------
--  DDL for Index KONTO_NR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBST49"."KONTO_NR_PK" ON "DBST49"."KONTO" ("KONTO_NR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00158017
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBST49"."SYS_C00158017" ON "DBST49"."KONTO" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00158019
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBST49"."SYS_C00158019" ON "DBST49"."ZWEIGSTELLE_V1" ("SYS_NC0000700008$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00158020
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBST49"."SYS_C00158020" ON "DBST49"."ZWEIGSTELLE_V1" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00158021
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBST49"."SYS_C00158021" ON "DBST49"."KUNDE_V1" ("SYS_NC0000800009$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00158022
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBST49"."SYS_C00158022" ON "DBST49"."KUNDE_V1" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table KONTO
--------------------------------------------------------

  ALTER TABLE "DBST49"."KONTO" ADD CONSTRAINT "KONTO_NR_PK" PRIMARY KEY ("KONTO_NR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBST49"."KONTO" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KUNDE_V1
--------------------------------------------------------

  ALTER TABLE "DBST49"."KUNDE_V1" ADD UNIQUE ("KUNDE_V1_KONTEN_LISTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBST49"."KUNDE_V1" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZWEIGSTELLE_V1
--------------------------------------------------------

  ALTER TABLE "DBST49"."ZWEIGSTELLE_V1" ADD UNIQUE ("ZWEIGSTELLE_V1_KONTEN_LISTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBST49"."ZWEIGSTELLE_V1" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  DDL for Synonymn DUAL
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DUAL" FOR "SYS"."DUAL";
