--------------------------------------------------------
--  Datei erstellt -Montag-Mai-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type ADRESSET
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST49"."ADRESSET" as Object
  ( Strasse VARCHAR2(50),
    Ort VARCHAR(50),
    Haus_Nr VARCHAR(25),
    Plz NUMBER(5,0)) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type KONTENLISTET
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST49"."KONTENLISTET" as Table of REF KontoT;

/
--------------------------------------------------------
--  DDL for Type KONTOT
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST49"."KONTOT" as Object
  ( Konto_Art VARCHAR(50),
    Konto_Nr NUMBER(9,0),
    Konto_Stand NUMBER) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type KUNDET_V1
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST49"."KUNDET_V1" as Object 
  ( Kunde_Nr NUMBER(4,0),
    Status VARCHAR2(25),
    Adresse REF AdresseT,
    Konto_Liste KontenListeT) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Type ZWEIGSTELLET_V1
--------------------------------------------------------

  CREATE OR REPLACE TYPE "DBST49"."ZWEIGSTELLET_V1" as Object
  ( Name_Zweigstelle VARCHAR2(50),
    Leiter VARCHAR(50),
    Adresse_Zweigstelle REF AdresseT,
    Konten_Liste KontenListeT) NOT FINAL;

/
--------------------------------------------------------
--  DDL for Table KONTEN
--------------------------------------------------------

  CREATE TABLE "DBST49"."KONTEN" OF "DBST49"."KONTOT" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
-- Wiedergabe von TABLE DDL für Objekt DBST49.KONTEN_LISTE_KUNDE_NT nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE TABLE KONTEN_LISTE_KUNDE_NT 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- Wiedergabe von TABLE DDL für Objekt DBST49.KONTEN_LISTE_ZWEIGSTELLE_NT nicht möglich, da DBMS_METADATA internen Generator versucht.
CREATE TABLE KONTEN_LISTE_ZWEIGSTELLE_NT 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
--------------------------------------------------------
--  DDL for Table KUNDE_V1
--------------------------------------------------------

  CREATE TABLE "DBST49"."KUNDE_V1" OF "DBST49"."KUNDET_V1" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 NESTED TABLE "KONTO_LISTE" STORE AS "KONTEN_LISTE_KUNDE_NT"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) RETURN AS VALUE;
--------------------------------------------------------
--  DDL for Table ZWEIGSTELLE_V1
--------------------------------------------------------

  CREATE TABLE "DBST49"."ZWEIGSTELLE_V1" OF "DBST49"."ZWEIGSTELLET_V1" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 NESTED TABLE "KONTEN_LISTE" STORE AS "KONTEN_LISTE_ZWEIGSTELLE_NT"
 (PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ) RETURN AS VALUE;
--------------------------------------------------------
--  DDL for View DMRS_INSTALLATION
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "DBST49"."DMRS_INSTALLATION" ("DMRS_PERSISTENCE_VERSION", "DMRS_REPORTS_VERSION", "CREATED_ON") AS 
  select 1.6 DMRS_Persistence_Version, 1.0 DMRS_Reports_Version, to_timestamp('2016/05/09 16:10:00','YYYY/MM/DD HH24:MI:SS') Created_On from dual with read only;
--------------------------------------------------------
--  DDL for View DMRV_REPORTS_VERSION_1_0
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "DBST49"."DMRV_REPORTS_VERSION_1_0" ("DMRS_PERSISTENCE_VERSION", "DMRS_REPORTS_VERSION", "CREATED_ON") AS 
  select 1.6 DMRS_Persistence_Version, 1.0 DMRS_Reports_Version, to_timestamp('2016/05/09 16:10:00','YYYY/MM/DD HH24:MI:SS') Created_On from dual with read only;
REM INSERTING into DBST49.KONTEN
SET DEFINE OFF;
REM INSERTING into DBST49.KUNDE_V1
SET DEFINE OFF;
REM INSERTING into DBST49.ZWEIGSTELLE_V1
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index KUNDE_NR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBST49"."KUNDE_NR_PK" ON "DBST49"."KUNDE_V1" ("KUNDE_NR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KONTO_NR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBST49"."KONTO_NR_PK" ON "DBST49"."KONTEN" ("KONTO_NR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NAME_ZWEIGSTELLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBST49"."NAME_ZWEIGSTELLE_PK" ON "DBST49"."ZWEIGSTELLE_V1" ("NAME_ZWEIGSTELLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table KONTEN
--------------------------------------------------------

  ALTER TABLE "DBST49"."KONTEN" ADD CONSTRAINT "KONTO_NR_PK" PRIMARY KEY ("KONTO_NR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBST49"."KONTEN" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZWEIGSTELLE_V1
--------------------------------------------------------

  ALTER TABLE "DBST49"."ZWEIGSTELLE_V1" ADD CONSTRAINT "NAME_ZWEIGSTELLE_PK" PRIMARY KEY ("NAME_ZWEIGSTELLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBST49"."ZWEIGSTELLE_V1" ADD UNIQUE ("KONTEN_LISTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBST49"."ZWEIGSTELLE_V1" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KUNDE_V1
--------------------------------------------------------

  ALTER TABLE "DBST49"."KUNDE_V1" ADD CONSTRAINT "KUNDE_NR_PK" PRIMARY KEY ("KUNDE_NR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBST49"."KUNDE_V1" ADD UNIQUE ("KONTO_LISTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DBST49"."KUNDE_V1" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
